version: "3.9"

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - .:/src
    environment:
      DJANGO_SETTINGS_MODULE: "settings.docker"
      POSTGRES_PASSWORD: "123"

  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "mydb"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
